### ISSUE TITLE
after update from 0.66.0 to 0.68.0 got JS error: _lib.customPropTypes.onlyProp is not a function

### ISSUE THREAD

**Issue by gshilin** [Semantic-Org/Semantic-UI-React#1595]
```
Uncaught TypeError: _lib.customPropTypes.onlyProp is not a function
    at Object.<anonymous> (GridColumn.js:91)
    at __webpack_require__ (bootstrap 53678e0…:555)
    at fn (bootstrap 53678e0…:86)
    at Object.<anonymous> (Grid.js:29)
    at __webpack_require__ (bootstrap 53678e0…:555)
    at fn (bootstrap 53678e0…:86)
    at Object.<anonymous> (index.js:8)
    at __webpack_require__ (bootstrap 53678e0…:555)
    at fn (bootstrap 53678e0…:86)
    at Object.<anonymous> (index.js:169)

**Comment by layershifter** [comment]
@gshilin What version of webpack do you use? There are no such problem neither in our docs nor locally with Webpack 2.

**Comment by gshilin** [comment]
I use webpack 1.14.0 from create-react-app

**Comment by layershifter** [comment]
Can you make a fresh install of deps? `rm -r node_modules; npm i`
I recently built successfully sample with [our example](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/examples/webpack1) config that uses webpack 1.

**Comment by gshilin** [comment]
Yes, it helped.
Thank you
