### ISSUE TITLE
TypeError: instance.render is not a function

### ISSUE THREAD

**Issue by yuchuan1** [Semantic-Org/Semantic-UI-React#2830]
## Bug Report
TypeError: instance.render is not a function
### Steps
I followed the example like so
```javascript
import React, { Component } from "react";
import { Button } from "semantic-ui-react";
import "semantic-ui-css/semantic.min.css";

class ButtonExampleButton extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    return (
      <Button>Click Here</Button>
    );
  }
}

export default ButtonExampleButton;
```
### Expected Result
It renders a button

### Actual Result
It gave an error

TypeError: instance.render is not a function
finishClassComponent
node_modules/react-dom/cjs/react-dom.development.js:8389

  8386 | } else {
  8387 |   {
  8388 |     ReactDebugCurrentFiber.setCurrentPhase('render');
  8389 |     nextChildren = instance.render();
  8390 |     if (debugRenderPhaseSideEffects || debugRenderPhaseSideEffectsForStrictMode && workInProgress.mode & StrictMode) {
  8391 |       instance.render();
  8392 |     }

### Version
0.80.0

**Comment by layershifter** [comment]
Looks like error in webpack config, see [codesandbox](https://codesandbox.io/s/5xp944xmml). It uses Creact React App, BTW.

Please check your environment.

**Comment by the-simian** [comment]
I am also getting this on version 80 and cannot proceed from 0.79, It may very well be a webpack config, but my existing config works 100% with 0.79.0.

**Comment by yuchuan1** [comment]
Yes, it works fine with 0.79.0. BTW, I am using create-react-app
